version: "3.8"
services:
  db:
    image: postgres:14
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:80"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
      
volumes:
  postgres-data:
